# 이 코드는 Python 프로젝트에서 pre-commit 툴을 사용하기 위한 설정 파일 (.pre-commit-config.yaml)입니다. pre-commit은 Git 커밋 전에 자동으로 코드 스타일 검사나 포맷팅을 실행하는 도구입니다. 각 repo는 검사할 도구의 위치이고, hooks는 어떤 검사를 실행할지를 지정합니다.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace # 줄 끝 공백 제거
      - id: end-of-file-fixer  # 파일 끝에 개행 한 줄 추가

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black   # 코드 자동 정렬 (PEP8 스타일)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"] # Black과 충돌 없도록 import 정렬

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: ["--max-line-length=92", "--ignore=F401"]  # 코드 검사 (lint), 사용하지 않는 import 무시
