# Generated by Django 5.2.4 on 2025-07-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="Restaurant",
            new_name="restaurant",
        ),
    ]
